#!/usr/bin/env bash
# CE Hub Appliance — Cyclone 6: persistent named cloudflared tunnel.
#
# Replaces the quick tunnel (URL rotates per restart, tunnels die every few
# minutes on UDP-buffer-constrained Pis) with a Cloudflare named tunnel —
# stable URL forever, no re-pairing on reboots.
#
# Prerequisite (run ONCE, interactive):
#   cloudflared tunnel login
#     → prints a Cloudflare URL. Visit it in any browser, authorize the
#       containedevolution.com zone. Cert lands at ~/.cloudflared/cert.pem.
#
# Then run this script (idempotent):
#   ./setup-cyclone6-tunnel.sh
#
# What it does:
#   1. Creates a `cehub-mcp` named tunnel (or reuses if it already exists)
#   2. Routes DNS: cehub-mcp.containedevolution.com → this tunnel
#   3. Writes ~/.cloudflared/config.yml pinning the tunnel to localhost:5984
#   4. Writes /etc/cehub/tunnel.env so the sidecar reads CEHUB_TUNNEL_URL
#      without parsing journalctl
#   5. Replaces /etc/systemd/system/cehub-tunnel.service with the
#      named-tunnel ExecStart
#   6. Restarts the service + verifies the public hostname returns 200
#
# Hostname choice: cehub-mcp.containedevolution.com (single-level so
# Cloudflare Universal SSL covers it for free). Two-level wildcards under
# *.hub.containedevolution.com would need Advanced Certificate Manager
# ($10/mo). For multi-tenant production we'll revisit the slug + ACM
# tradeoff; for now single-Pi means single hostname is fine.

set -euo pipefail

if [[ $EUID -eq 0 ]]; then
  echo "Run as your normal user (not root). Uses sudo internally."
  exit 1
fi

TUNNEL_NAME="${TUNNEL_NAME:-cehub-mcp}"
HOSTNAME="${HOSTNAME:-cehub-mcp.containedevolution.com}"
TUNNEL_ENV_DIR="/etc/cehub"
TUNNEL_ENV_FILE="$TUNNEL_ENV_DIR/tunnel.env"
CONFIG_YML="$HOME/.cloudflared/config.yml"

if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
  echo "ERROR: $HOME/.cloudflared/cert.pem not found."
  echo "  Run: cloudflared tunnel login"
  echo "  Then visit the printed URL in a browser to authorize containedevolution.com."
  exit 1
fi

echo "==> [1/6] Create tunnel '$TUNNEL_NAME' (idempotent)"
cloudflared tunnel create "$TUNNEL_NAME" 2>&1 | grep -v 'level":"warn' || true

echo "==> [2/6] Resolve tunnel UUID"
TUNNEL_UUID=$(cloudflared tunnel list --output json 2>/dev/null \
  | python3 -c "import json,sys; ts=json.load(sys.stdin); print(next((t['id'] for t in ts if t['name']=='$TUNNEL_NAME'), ''))")
if [[ -z "$TUNNEL_UUID" ]]; then
  echo "ERROR: could not resolve UUID for tunnel '$TUNNEL_NAME'."
  exit 1
fi
echo "    UUID = $TUNNEL_UUID"

echo "==> [3/6] Route DNS: $HOSTNAME → tunnel"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" 2>&1 \
  | grep -v 'level":"warn' \
  || echo "    (CNAME may already exist — continuing)"

echo "==> [4/6] Write $CONFIG_YML"
mkdir -p "$HOME/.cloudflared"
cat > "$CONFIG_YML" <<EOF
# Generated by setup-cyclone6-tunnel.sh — Cyclone 6 named tunnel.
tunnel: $TUNNEL_UUID
credentials-file: $HOME/.cloudflared/$TUNNEL_UUID.json

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:5984
  - service: http_status:404
EOF

echo "==> [5/6] Write $TUNNEL_ENV_FILE (read by cehub.service)"
sudo mkdir -p "$TUNNEL_ENV_DIR"
sudo tee "$TUNNEL_ENV_FILE" >/dev/null <<EOF
# Generated by setup-cyclone6-tunnel.sh
# lib/tunnel-detect.js prefers this env over journalctl parsing,
# so the sidecar always reports the stable named-tunnel URL.
CEHUB_TUNNEL_URL=https://$HOSTNAME
EOF

echo "==> [6/6] Replace cehub-tunnel.service with named-tunnel unit"
sudo tee /etc/systemd/system/cehub-tunnel.service >/dev/null <<EOF
[Unit]
Description=CE Hub Appliance — cloudflared named tunnel (Cyclone 6, persistent URL)
After=cehub.service
Requires=cehub.service

[Service]
Type=simple
User=$(whoami)
# --protocol http2 keeps tunnels stable on the Pi (UDP receive buffer is
# capped well below what QUIC wants → packet loss → cycling).
ExecStart=/usr/local/bin/cloudflared tunnel --protocol http2 --no-autoupdate run $TUNNEL_NAME
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl restart cehub-tunnel.service
sudo systemctl restart cehub.service   # picks up new tunnel.env

echo
echo "==> Waiting 15s for tunnel + sidecar to come up…"
sleep 15

echo "==> Verify public hostname"
HTTP_CODE=$(curl -s -o /tmp/cyclone6-verify -w "%{http_code}" "https://$HOSTNAME/pair" || echo "000")
echo "    HTTP $HTTP_CODE"
if [[ "$HTTP_CODE" != "200" ]]; then
  echo "    Body:"
  cat /tmp/cyclone6-verify | head -20
  rm -f /tmp/cyclone6-verify
  echo
  echo "ERROR: verification failed. Check:"
  echo "    sudo journalctl -u cehub-tunnel.service -n 30 --no-pager"
  exit 1
fi
echo "    Body:"
cat /tmp/cyclone6-verify
rm -f /tmp/cyclone6-verify
echo

echo "==> Cyclone 6 ready. Stable tunnel URL: https://$HOSTNAME"
echo "==> Pair in Settings → Integrations once. Then never again — URL persists across reboots."
