'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const express = require('express');
const { createAppStore } = require('./app-store');
const { createRegistry } = require('./app-registry');

test('store requires a local surface and install token, then installs and opens a verified app', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'shell-store-'));
  t.after(() => fs.rmSync(root, {recursive:true,force:true}));
  const catalogDirectory = path.join(root, 'catalog');
  const appsDirectory = path.join(root, 'apps');
  fs.mkdirSync(catalogDirectory);
  const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
  const manifest = {contractVersion:1,id:'scribble',name:'Scribble',version:'0.2.0',entrypoints:{web:'web/index.html'},capabilities:[]};
  const files = {'app.manifest.json':JSON.stringify(manifest),'web/index.html':'<h1>Scribble</h1>'};
  const release = Buffer.from(JSON.stringify({contractVersion:1,kind:'ce.app.release',id:'scribble',version:'0.2.0',files:Object.entries(files).map(([name,content])=>({path:name,encoding:'base64',content:Buffer.from(content).toString('base64'),sha256:hash(content)}))}));
  fs.writeFileSync(path.join(catalogDirectory,'scribble.ceapp.json'),release);
  fs.writeFileSync(path.join(catalogDirectory,'catalog.json'),JSON.stringify({contractVersion:1,apps:[{id:'scribble',name:'Scribble',version:'0.2.0',file:'scribble.ceapp.json',sha256:hash(release)}]}));
  const app = express(); app.use('/v1/app-store',createAppStore({catalogDirectory,appsDirectory})); app.use('/v1/apps',createRegistry(appsDirectory).router());
  const server = app.listen(0,'127.0.0.1'); await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const url = origin + '/v1/app-store';
  assert.equal((await fetch(url,{headers:{Origin:'https://app.tenari.world'}})).status,403);
  const catalog = await (await fetch(url)).json();
  assert.equal(catalog.apps[0].installedVersion,null);
  assert.equal((await fetch(url+'/scribble/install',{method:'POST'})).status,403);
  const headers = {'X-Shell-Install':catalog.installToken,Origin:origin};
  assert.equal((await fetch(url+'/scribble/install',{method:'POST',headers})).status,201);
  assert.equal((await fetch(url+'/scribble/install',{method:'POST',headers})).status,200);
  assert.equal((await fetch(url+'/unknown/install',{method:'POST',headers})).status,404);
  const installed = await (await fetch(url)).json();
  assert.equal(installed.apps[0].installedVersion,'0.2.0');
  assert.equal(await (await fetch(origin+installed.apps[0].launchUrl)).text(),'<h1>Scribble</h1>');
  fs.appendFileSync(path.join(catalogDirectory,'scribble.ceapp.json'),'tampered');
  assert.equal((await fetch(url)).status,503);
  assert.equal((await fetch(origin+installed.apps[0].launchUrl)).status,200);
});
